WORKOUTS_DB = [
    {
        "id": 1,
        "name": "Push-Up",
        "category": "home",
        "sub_category": "no_equipment",
        "muscle_group": "chest",
        "secondary_muscles": ["triceps", "front_delt", "core"],
        "equipment": "bodyweight",
        "equipment_required": False,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "push",
        "is_compound": True,
        "instructions": "Start in a high plank position with your hands slightly wider than shoulder width. Lower your chest toward the floor and push back up while keeping your body straight.",
        "recommended_sets": 3,
        "recommended_reps": "10-20"
    },
    {
        "id": 2,
        "name": "Bodyweight Squat",
        "category": "home",
        "sub_category": "no_equipment",
        "muscle_group": "quadriceps",
        "secondary_muscles": ["glutes", "hamstrings", "core"],
        "equipment": "bodyweight",
        "equipment_required": False,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "squat",
        "is_compound": True,
        "instructions": "Stand with your feet approximately shoulder width apart. Push your hips back, bend your knees and lower your body, then drive through your feet to stand.",
        "recommended_sets": 3,
        "recommended_reps": "15-20"
    },
    {
        "id": 3,
        "name": "Walking Lunges",
        "category": "home",
        "sub_category": "no_equipment",
        "muscle_group": "quadriceps",
        "secondary_muscles": ["glutes", "hamstrings", "core"],
        "equipment": "bodyweight",
        "equipment_required": False,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "lunge",
        "is_compound": True,
        "instructions": "Step forward with one leg, lower your hips until both knees are bent, push through the front foot and step forward with the opposite leg.",
        "recommended_sets": 3,
        "recommended_reps": "10-12 each leg"
    },
    {
        "id": 4,
        "name": "Mountain Climbers",
        "category": "home",
        "sub_category": "no_equipment",
        "muscle_group": "core",
        "secondary_muscles": ["shoulders", "quadriceps", "hip_flexors"],
        "equipment": "bodyweight",
        "equipment_required": False,
        "difficulty": "beginner",
        "exercise_type": "cardio",
        "movement_type": "conditioning",
        "is_compound": True,
        "instructions": "Start in a high plank position. Drive one knee toward your chest, return it, then alternate legs rapidly while maintaining a stable plank position.",
        "recommended_sets": 3,
        "recommended_reps": "30-45 sec"
    },
    {
        "id": 5,
        "name": "Resistance Band Chest Press",
        "category": "home",
        "sub_category": "minimal_equipment",
        "muscle_group": "chest",
        "secondary_muscles": ["triceps", "front_delt"],
        "equipment": "resistance_band",
        "equipment_required": True,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "push",
        "is_compound": True,
        "instructions": "Anchor the resistance band behind you at chest height. Hold the handles and press your hands forward until your arms are extended.",
        "recommended_sets": 3,
        "recommended_reps": "12-15"
    },
    {
        "id": 6,
        "name": "Resistance Band Row",
        "category": "home",
        "sub_category": "minimal_equipment",
        "muscle_group": "back",
        "secondary_muscles": ["biceps", "rear_delt"],
        "equipment": "resistance_band",
        "equipment_required": True,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "pull",
        "is_compound": True,
        "instructions": "Secure the resistance band at a stable point. Pull the handles toward your torso while squeezing your shoulder blades together.",
        "recommended_sets": 3,
        "recommended_reps": "12-15"
    },
    {
        "id": 7,
        "name": "Dumbbell Goblet Squat",
        "category": "home",
        "sub_category": "equipment",
        "muscle_group": "quadriceps",
        "secondary_muscles": ["glutes", "hamstrings", "core"],
        "equipment": "dumbbell",
        "equipment_required": True,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "squat",
        "is_compound": True,
        "instructions": "Hold one dumbbell vertically against your chest. Squat down while keeping your chest upright, then drive through your feet to return to standing.",
        "recommended_sets": 3,
        "recommended_reps": "10-15"
    },
    {
        "id": 8,
        "name": "Barbell Bench Press",
        "category": "gym",
        "sub_category": "barbell",
        "muscle_group": "chest",
        "secondary_muscles": ["triceps", "front_delt"],
        "equipment": "barbell",
        "equipment_required": True,
        "difficulty": "intermediate",
        "exercise_type": "strength",
        "movement_type": "push",
        "is_compound": True,
        "instructions": "Lie flat on the bench, grip the barbell slightly wider than shoulder width, lower it toward your mid-chest and press it upward smoothly.",
        "recommended_sets": 4,
        "recommended_reps": "8-12"
    },
    {
        "id": 9,
        "name": "Barbell Back Squat",
        "category": "gym",
        "sub_category": "barbell",
        "muscle_group": "quadriceps",
        "secondary_muscles": ["glutes", "hamstrings", "core"],
        "equipment": "barbell",
        "equipment_required": True,
        "difficulty": "intermediate",
        "exercise_type": "strength",
        "movement_type": "squat",
        "is_compound": True,
        "instructions": "Place the barbell across your upper back. Brace your core, squat down under control and drive through your feet to return to standing.",
        "recommended_sets": 4,
        "recommended_reps": "6-10"
    },
    {
        "id": 10,
        "name": "Dumbbell Shoulder Press",
        "category": "gym",
        "sub_category": "dumbbell",
        "muscle_group": "shoulders",
        "secondary_muscles": ["triceps", "upper_chest"],
        "equipment": "dumbbell",
        "equipment_required": True,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "push",
        "is_compound": True,
        "instructions": "Sit upright with dumbbells at shoulder level. Press them overhead until your arms are extended and slowly return.",
        "recommended_sets": 3,
        "recommended_reps": "8-12"
    },
    {
        "id": 11,
        "name": "Lat Pulldown",
        "category": "gym",
        "sub_category": "cable",
        "muscle_group": "lats",
        "secondary_muscles": ["biceps", "rear_delt"],
        "equipment": "cable_machine",
        "equipment_required": True,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "pull",
        "is_compound": True,
        "instructions": "Grip the bar slightly wider than shoulder width. Pull the bar toward your upper chest while keeping your torso stable, then slowly return.",
        "recommended_sets": 3,
        "recommended_reps": "8-12"
    },
    {
        "id": 12,
        "name": "Leg Press",
        "category": "gym",
        "sub_category": "machine",
        "muscle_group": "quadriceps",
        "secondary_muscles": ["glutes", "hamstrings"],
        "equipment": "leg_press_machine",
        "equipment_required": True,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "squat",
        "is_compound": True,
        "instructions": "Place your feet on the platform, lower the weight by bending your knees, then press the platform away without locking your knees.",
        "recommended_sets": 3,
        "recommended_reps": "10-15"
    },
    {
        "id": 13,
        "name": "Burpees",
        "category": "cardio",
        "sub_category": "hiit",
        "muscle_group": "full_body",
        "secondary_muscles": ["chest", "shoulders", "quadriceps", "glutes", "core"],
        "equipment": "bodyweight",
        "equipment_required": False,
        "difficulty": "intermediate",
        "exercise_type": "cardio",
        "movement_type": "conditioning",
        "is_compound": True,
        "instructions": "Start standing, squat down and place your hands on the floor, jump your feet back into a plank, return your feet forward and jump upward.",
        "recommended_sets": 4,
        "recommended_reps": "10-15"
    },
    {
        "id": 14,
        "name": "Diamond Push-Up",
        "category": "home",
        "sub_category": "no_equipment",
        "muscle_group": "triceps",
        "secondary_muscles": ["chest", "front_delt", "core"],
        "equipment": "bodyweight",
        "equipment_required": False,
        "difficulty": "intermediate",
        "exercise_type": "strength",
        "movement_type": "push",
        "is_compound": True,
        "instructions": "Start in a push-up position with your hands close together forming a diamond shape. Lower your chest toward your hands and press back up while keeping your body straight.",
        "recommended_sets": 3,
        "recommended_reps": "8-15"
    },
    {
        "id": 15,
        "name": "Decline Push-Up",
        "category": "home",
        "sub_category": "no_equipment",
        "muscle_group": "upper_chest",
        "secondary_muscles": ["triceps", "front_delt", "core"],
        "equipment": "bodyweight",
        "equipment_required": False,
        "difficulty": "intermediate",
        "exercise_type": "strength",
        "movement_type": "push",
        "is_compound": True,
        "instructions": "Place your feet on an elevated surface and your hands on the floor. Lower your chest toward the floor and press back up while maintaining a straight body.",
        "recommended_sets": 3,
        "recommended_reps": "8-15"
    },
    {
        "id": 16,
        "name": "Wide Push-Up",
        "category": "home",
        "sub_category": "no_equipment",
        "muscle_group": "chest",
        "secondary_muscles": ["front_delt", "triceps"],
        "equipment": "bodyweight",
        "equipment_required": False,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "push",
        "is_compound": True,
        "instructions": "Place your hands wider than shoulder width. Lower your chest toward the floor while keeping your core tight, then push back up.",
        "recommended_sets": 3,
        "recommended_reps": "10-20"
    },
    {
        "id": 17,
        "name": "Pike Push-Up",
        "category": "home",
        "sub_category": "no_equipment",
        "muscle_group": "shoulders",
        "secondary_muscles": ["triceps", "upper_chest", "core"],
        "equipment": "bodyweight",
        "equipment_required": False,
        "difficulty": "intermediate",
        "exercise_type": "strength",
        "movement_type": "push",
        "is_compound": True,
        "instructions": "Start in a downward-facing V position with your hips raised. Bend your elbows and lower your head toward the floor, then press back up.",
        "recommended_sets": 3,
        "recommended_reps": "8-15"
    },
    {
        "id": 18,
        "name": "Diamond Squat",
        "category": "home",
        "sub_category": "no_equipment",
        "muscle_group": "quadriceps",
        "secondary_muscles": ["glutes", "hamstrings"],
        "equipment": "bodyweight",
        "equipment_required": False,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "squat",
        "is_compound": True,
        "instructions": "Stand with your feet close together and toes slightly turned out. Lower into a squat while keeping your chest upright, then return to standing.",
        "recommended_sets": 3,
        "recommended_reps": "15-20"
    },
    {
        "id": 19,
        "name": "Reverse Lunge",
        "category": "home",
        "sub_category": "no_equipment",
        "muscle_group": "glutes",
        "secondary_muscles": ["quadriceps", "hamstrings", "core"],
        "equipment": "bodyweight",
        "equipment_required": False,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "lunge",
        "is_compound": True,
        "instructions": "Step backward with one leg and lower your body until both knees are bent. Push through the front foot to return to standing.",
        "recommended_sets": 3,
        "recommended_reps": "10-12 each leg"
    },
    {
        "id": 20,
        "name": "Glute Bridge",
        "category": "home",
        "sub_category": "no_equipment",
        "muscle_group": "glutes",
        "secondary_muscles": ["hamstrings", "core"],
        "equipment": "bodyweight",
        "equipment_required": False,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "hip_extension",
        "is_compound": True,
        "instructions": "Lie on your back with your knees bent and feet flat. Drive your hips upward, squeeze your glutes at the top and slowly lower.",
        "recommended_sets": 3,
        "recommended_reps": "15-20"
    },
    {
        "id": 21,
        "name": "Single-Leg Glute Bridge",
        "category": "home",
        "sub_category": "no_equipment",
        "muscle_group": "glutes",
        "secondary_muscles": ["hamstrings", "core"],
        "equipment": "bodyweight",
        "equipment_required": False,
        "difficulty": "intermediate",
        "exercise_type": "strength",
        "movement_type": "hip_extension",
        "is_compound": False,
        "instructions": "Lie on your back with one foot on the floor and the other leg extended. Drive through the planted foot to raise your hips and squeeze your glute.",
        "recommended_sets": 3,
        "recommended_reps": "10-15 each leg"
    },
    {
        "id": 22,
        "name": "Bodyweight Calf Raise",
        "category": "home",
        "sub_category": "no_equipment",
        "muscle_group": "calves",
        "secondary_muscles": [],
        "equipment": "bodyweight",
        "equipment_required": False,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "calf_raise",
        "is_compound": False,
        "instructions": "Stand upright with your feet hip width apart. Raise your heels as high as possible, pause at the top and slowly lower them.",
        "recommended_sets": 4,
        "recommended_reps": "15-25"
    },
    {
        "id": 23,
        "name": "Crunch",
        "category": "home",
        "sub_category": "no_equipment",
        "muscle_group": "abs",
        "secondary_muscles": [],
        "equipment": "bodyweight",
        "equipment_required": False,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "flexion",
        "is_compound": False,
        "instructions": "Lie on your back with your knees bent. Contract your abs and lift your shoulders from the floor without pulling on your neck.",
        "recommended_sets": 3,
        "recommended_reps": "15-20"
    },
    {
        "id": 24,
        "name": "Bicycle Crunch",
        "category": "home",
        "sub_category": "no_equipment",
        "muscle_group": "abs",
        "secondary_muscles": ["obliques"],
        "equipment": "bodyweight",
        "equipment_required": False,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "rotation",
        "is_compound": False,
        "instructions": "Lie on your back with your hands behind your head. Bring one knee toward your chest while rotating your torso toward it, then alternate sides.",
        "recommended_sets": 3,
        "recommended_reps": "16-24"
    },
    {
        "id": 25,
        "name": "Leg Raise",
        "category": "home",
        "sub_category": "no_equipment",
        "muscle_group": "lower_abs",
        "secondary_muscles": ["hip_flexors"],
        "equipment": "bodyweight",
        "equipment_required": False,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "flexion",
        "is_compound": False,
        "instructions": "Lie flat on your back with your legs extended. Keeping your legs together, raise them toward the ceiling and slowly lower them without arching your lower back.",
        "recommended_sets": 3,
        "recommended_reps": "10-15"
    },
    {
        "id": 26,
        "name": "Dead Bug",
        "category": "home",
        "sub_category": "no_equipment",
        "muscle_group": "core",
        "secondary_muscles": ["abs", "hip_flexors"],
        "equipment": "bodyweight",
        "equipment_required": False,
        "difficulty": "beginner",
        "exercise_type": "core",
        "movement_type": "stability",
        "is_compound": True,
        "instructions": "Lie on your back with your arms and knees raised. Slowly extend the opposite arm and leg while keeping your lower back pressed into the floor.",
        "recommended_sets": 3,
        "recommended_reps": "8-12 each side"
    },
    {
        "id": 27,
        "name": "Bird Dog",
        "category": "home",
        "sub_category": "no_equipment",
        "muscle_group": "core",
        "secondary_muscles": ["glutes", "lower_back", "shoulders"],
        "equipment": "bodyweight",
        "equipment_required": False,
        "difficulty": "beginner",
        "exercise_type": "core",
        "movement_type": "stability",
        "is_compound": True,
        "instructions": "Start on your hands and knees. Extend one arm and the opposite leg simultaneously while keeping your hips stable, then return and switch sides.",
        "recommended_sets": 3,
        "recommended_reps": "8-12 each side"
    },
    {
        "id": 28,
        "name": "Dumbbell Floor Press",
        "category": "home",
        "sub_category": "dumbbell",
        "muscle_group": "chest",
        "secondary_muscles": ["triceps", "front_delt"],
        "equipment": "dumbbell",
        "equipment_required": True,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "push",
        "is_compound": True,
        "instructions": "Lie on the floor holding dumbbells above your chest. Lower the dumbbells until your upper arms touch the floor, then press them upward.",
        "recommended_sets": 3,
        "recommended_reps": "8-12"
    },
    {
        "id": 29,
        "name": "Dumbbell Romanian Deadlift",
        "category": "home",
        "sub_category": "dumbbell",
        "muscle_group": "hamstrings",
        "secondary_muscles": ["glutes", "lower_back"],
        "equipment": "dumbbell",
        "equipment_required": True,
        "difficulty": "intermediate",
        "exercise_type": "strength",
        "movement_type": "hinge",
        "is_compound": True,
        "instructions": "Hold dumbbells in front of your thighs. Push your hips backward while maintaining a neutral spine, lower the weights along your legs, then drive your hips forward.",
        "recommended_sets": 3,
        "recommended_reps": "8-12"
    },
    {
        "id": 30,
        "name": "Dumbbell Bent-Over Row",
        "category": "home",
        "sub_category": "dumbbell",
        "muscle_group": "back",
        "secondary_muscles": ["biceps", "rear_delt"],
        "equipment": "dumbbell",
        "equipment_required": True,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "pull",
        "is_compound": True,
        "instructions": "Hinge forward with a neutral spine while holding dumbbells. Pull the weights toward your hips and squeeze your shoulder blades together.",
        "recommended_sets": 3,
        "recommended_reps": "8-12"
    },
    {
        "id": 31,
        "name": "Dumbbell Lateral Raise",
        "category": "home",
        "sub_category": "dumbbell",
        "muscle_group": "side_delt",
        "secondary_muscles": ["traps"],
        "equipment": "dumbbell",
        "equipment_required": True,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "isolation",
        "is_compound": False,
        "instructions": "Stand holding dumbbells at your sides. Raise your arms outward until approximately shoulder height and slowly lower them.",
        "recommended_sets": 3,
        "recommended_reps": "12-15"
    },
    {
        "id": 32,
        "name": "Dumbbell Biceps Curl",
        "category": "home",
        "sub_category": "dumbbell",
        "muscle_group": "biceps",
        "secondary_muscles": ["forearms"],
        "equipment": "dumbbell",
        "equipment_required": True,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "curl",
        "is_compound": False,
        "instructions": "Hold dumbbells with your palms facing forward. Curl the weights toward your shoulders while keeping your elbows close to your body.",
        "recommended_sets": 3,
        "recommended_reps": "10-15"
    },
    {
        "id": 33,
        "name": "Band Squat",
        "category": "home",
        "sub_category": "resistance_bands",
        "muscle_group": "quadriceps",
        "secondary_muscles": ["glutes", "hamstrings"],
        "equipment": "resistance_band",
        "equipment_required": True,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "squat",
        "is_compound": True,
        "instructions": "Stand on the resistance band and hold the handles at shoulder level. Perform a controlled squat while maintaining tension on the band.",
        "recommended_sets": 3,
        "recommended_reps": "12-15"
    },
    {
        "id": 34,
        "name": "Band Biceps Curl",
        "category": "home",
        "sub_category": "resistance_bands",
        "muscle_group": "biceps",
        "secondary_muscles": ["forearms"],
        "equipment": "resistance_band",
        "equipment_required": True,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "curl",
        "is_compound": False,
        "instructions": "Stand on the resistance band and hold the handles with your palms facing forward. Curl your hands toward your shoulders while keeping your elbows stationary.",
        "recommended_sets": 3,
        "recommended_reps": "12-15"
    },
    {
        "id": 35,
        "name": "Band Lateral Walk",
        "category": "home",
        "sub_category": "resistance_bands",
        "muscle_group": "glutes",
        "secondary_muscles": ["hip_abductors", "quadriceps"],
        "equipment": "resistance_band",
        "equipment_required": True,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "abduction",
        "is_compound": False,
        "instructions": "Place a resistance band around your thighs or ankles. Bend slightly at the knees and take controlled sideways steps while maintaining band tension.",
        "recommended_sets": 3,
        "recommended_reps": "12-15 each side"
    },
    {
        "id": 36,
        "name": "Conventional Deadlift",
        "category": "gym",
        "sub_category": "barbell",
        "muscle_group": "hamstrings",
        "secondary_muscles": ["glutes", "lower_back", "core", "forearms"],
        "equipment": "barbell",
        "equipment_required": True,
        "difficulty": "advanced",
        "exercise_type": "strength",
        "movement_type": "hinge",
        "is_compound": True,
        "instructions": "Stand with the bar over your mid-foot. Hinge at your hips, grip the bar, brace your core and drive through the floor to stand.",
        "recommended_sets": 4,
        "recommended_reps": "5-8"
    },
    {
        "id": 37,
        "name": "Barbell Romanian Deadlift",
        "category": "gym",
        "sub_category": "barbell",
        "muscle_group": "hamstrings",
        "secondary_muscles": ["glutes", "lower_back"],
        "equipment": "barbell",
        "equipment_required": True,
        "difficulty": "intermediate",
        "exercise_type": "strength",
        "movement_type": "hinge",
        "is_compound": True,
        "instructions": "Hold the bar in front of your thighs. Push your hips backward while maintaining a neutral spine, lower the bar along your legs and return to standing.",
        "recommended_sets": 3,
        "recommended_reps": "8-12"
    },
    {
        "id": 38,
        "name": "Barbell Overhead Press",
        "category": "gym",
        "sub_category": "barbell",
        "muscle_group": "shoulders",
        "secondary_muscles": ["triceps", "upper_chest", "core"],
        "equipment": "barbell",
        "equipment_required": True,
        "difficulty": "intermediate",
        "exercise_type": "strength",
        "movement_type": "push",
        "is_compound": True,
        "instructions": "Hold the bar at shoulder height. Brace your core and press the bar overhead until your arms are extended, then lower it under control.",
        "recommended_sets": 4,
        "recommended_reps": "6-10"
    },
    {
        "id": 39,
        "name": "Barbell Bent-Over Row",
        "category": "gym",
        "sub_category": "barbell",
        "muscle_group": "back",
        "secondary_muscles": ["biceps", "rear_delt", "lower_back"],
        "equipment": "barbell",
        "equipment_required": True,
        "difficulty": "intermediate",
        "exercise_type": "strength",
        "movement_type": "pull",
        "is_compound": True,
        "instructions": "Hinge forward with a neutral spine. Pull the bar toward your lower ribs while keeping your elbows close to your body.",
        "recommended_sets": 4,
        "recommended_reps": "8-12"
    },
    {
        "id": 40,
        "name": "Cable Chest Fly",
        "category": "gym",
        "sub_category": "cable",
        "muscle_group": "chest",
        "secondary_muscles": ["front_delt"],
        "equipment": "cable_machine",
        "equipment_required": True,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "fly",
        "is_compound": False,
        "instructions": "Stand between two cable handles. With a slight bend in your elbows, bring your hands together in front of your chest and slowly return.",
        "recommended_sets": 3,
        "recommended_reps": "10-15"
    },
    {
        "id": 41,
        "name": "Cable Triceps Pushdown",
        "category": "gym",
        "sub_category": "cable",
        "muscle_group": "triceps",
        "secondary_muscles": [],
        "equipment": "cable_machine",
        "equipment_required": True,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "extension",
        "is_compound": False,
        "instructions": "Attach a rope or bar to a high cable. Keep your elbows close to your body and push the handle downward until your arms are extended.",
        "recommended_sets": 3,
        "recommended_reps": "10-15"
    },
    {
        "id": 42,
        "name": "Cable Face Pull",
        "category": "gym",
        "sub_category": "cable",
        "muscle_group": "rear_delt",
        "secondary_muscles": ["traps", "rotator_cuff"],
        "equipment": "cable_machine",
        "equipment_required": True,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "pull",
        "is_compound": False,
        "instructions": "Attach a rope to a high cable. Pull the rope toward your face while separating your hands and squeezing your rear shoulders.",
        "recommended_sets": 3,
        "recommended_reps": "12-15"
    },
    {
        "id": 43,
        "name": "Cable Biceps Curl",
        "category": "gym",
        "sub_category": "cable",
        "muscle_group": "biceps",
        "secondary_muscles": ["forearms"],
        "equipment": "cable_machine",
        "equipment_required": True,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "curl",
        "is_compound": False,
        "instructions": "Attach a straight bar to a low cable. Keep your elbows close to your sides and curl the bar toward your shoulders.",
        "recommended_sets": 3,
        "recommended_reps": "10-15"
    },
    {
        "id": 44,
        "name": "Chest Press Machine",
        "category": "gym",
        "sub_category": "machine",
        "muscle_group": "chest",
        "secondary_muscles": ["triceps", "front_delt"],
        "equipment": "chest_press_machine",
        "equipment_required": True,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "push",
        "is_compound": True,
        "instructions": "Adjust the seat so the handles are around chest height. Push the handles forward until your arms are extended, then return slowly.",
        "recommended_sets": 3,
        "recommended_reps": "8-12"
    },
    {
        "id": 45,
        "name": "Seated Row Machine",
        "category": "gym",
        "sub_category": "machine",
        "muscle_group": "back",
        "secondary_muscles": ["biceps", "rear_delt"],
        "equipment": "row_machine",
        "equipment_required": True,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "pull",
        "is_compound": True,
        "instructions": "Sit upright and grip the handles. Pull them toward your torso while squeezing your shoulder blades, then slowly return.",
        "recommended_sets": 3,
        "recommended_reps": "8-12"
    },
    {
        "id": 46,
        "name": "Leg Extension Machine",
        "category": "gym",
        "sub_category": "machine",
        "muscle_group": "quadriceps",
        "secondary_muscles": [],
        "equipment": "leg_extension_machine",
        "equipment_required": True,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "extension",
        "is_compound": False,
        "instructions": "Sit with your ankles behind the machine pads. Extend your legs until nearly straight, squeeze your quadriceps and slowly return.",
        "recommended_sets": 3,
        "recommended_reps": "12-15"
    },
    {
        "id": 47,
        "name": "Seated Leg Curl",
        "category": "gym",
        "sub_category": "machine",
        "muscle_group": "hamstrings",
        "secondary_muscles": ["calves"],
        "equipment": "leg_curl_machine",
        "equipment_required": True,
        "difficulty": "beginner",
        "exercise_type": "strength",
        "movement_type": "curl",
        "is_compound": False,
        "instructions": "Sit with your legs positioned under the pads. Curl your heels downward and backward, squeeze your hamstrings and slowly return.",
        "recommended_sets": 3,
        "recommended_reps": "10-15"
    },
    {
        "id": 48,
        "name": "Jumping Jacks",
        "category": "cardio",
        "sub_category": "cardio",
        "muscle_group": "full_body",
        "secondary_muscles": ["calves", "shoulders", "core"],
        "equipment": "bodyweight",
        "equipment_required": False,
        "difficulty": "beginner",
        "exercise_type": "cardio",
        "movement_type": "conditioning",
        "is_compound": True,
        "instructions": "Stand with your feet together. Jump while spreading your legs and raising your arms overhead, then return to the starting position.",
        "recommended_sets": 3,
        "recommended_reps": "30-60 sec"
    },
    {
        "id": 49,
        "name": "High Knees",
        "category": "cardio",
        "sub_category": "cardio",
        "muscle_group": "full_body",
        "secondary_muscles": ["quadriceps", "calves", "core"],
        "equipment": "bodyweight",
        "equipment_required": False,
        "difficulty": "beginner",
        "exercise_type": "cardio",
        "movement_type": "conditioning",
        "is_compound": True,
        "instructions": "Run in place while driving your knees upward toward your chest. Maintain a fast but controlled pace.",
        "recommended_sets": 3,
        "recommended_reps": "30-60 sec"
    },
    {
        "id": 50,
        "name": "Squat Jump",
        "category": "cardio",
        "sub_category": "hiit",
        "muscle_group": "quadriceps",
        "secondary_muscles": ["glutes", "calves", "core"],
        "equipment": "bodyweight",
        "equipment_required": False,
        "difficulty": "intermediate",
        "exercise_type": "plyometric",
        "movement_type": "jump",
        "is_compound": True,
        "instructions": "Lower into a squat and explosively jump upward. Land softly with bent knees and immediately prepare for the next repetition.",
        "recommended_sets": 3,
        "recommended_reps": "10-15"
    },
    {
        "id": 51,
        "name": "Burpee",
        "category": "cardio",
        "sub_category": "hiit",
        "muscle_group": "full_body",
        "secondary_muscles": ["chest", "shoulders", "quadriceps", "glutes", "core"],
        "equipment": "bodyweight",
        "equipment_required": False,
        "difficulty": "advanced",
        "exercise_type": "conditioning",
        "movement_type": "full_body",
        "is_compound": True,
        "instructions": "Squat down, place your hands on the floor, jump your feet backward into a plank, return your feet forward and explosively jump upward.",
        "recommended_sets": 4,
        "recommended_reps": "8-15"
    },
    {
        "id": 52,
        "name": "Cat-Cow Stretch",
        "category": "mobility",
        "sub_category": "mobility",
        "muscle_group": "spine",
        "secondary_muscles": ["core", "shoulders"],
        "equipment": "bodyweight",
        "equipment_required": False,
        "difficulty": "beginner",
        "exercise_type": "mobility",
        "movement_type": "spinal_mobility",
        "is_compound": True,
        "instructions": "Start on your hands and knees. Alternate between gently arching your spine upward and extending it downward while moving slowly with your breathing.",
        "recommended_sets": 2,
        "recommended_reps": "8-12"
    },
    {
        "id": 53,
        "name": "World's Greatest Stretch",
        "category": "mobility",
        "sub_category": "mobility",
        "muscle_group": "full_body",
        "secondary_muscles": ["hips", "hamstrings", "thoracic_spine"],
        "equipment": "bodyweight",
        "equipment_required": False,
        "difficulty": "beginner",
        "exercise_type": "mobility",
        "movement_type": "stretch",
        "is_compound": True,
        "instructions": "Step into a deep lunge, place both hands near your front foot, rotate your torso and reach one arm toward the ceiling before switching sides.",
        "recommended_sets": 2,
        "recommended_reps": "5-8 each side"
    }
]